using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Map;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class StationMapUiFragment : Robust.Client.UserInterface.Controls.BoxContainer
{

    public StationMapUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Set(EntityUid? mapUid, EntityUid? trackedEntity)
    {
        NavMapScreen.MapUid = mapUid;

        if (trackedEntity != null)
            NavMapScreen.TrackedCoordinates.Add(new EntityCoordinates(trackedEntity.Value, System.Numerics.Vector2.Zero), (true, Color.Cyan));

        NavMapScreen.ForceNavMapUpdate();
    }
}
